scrape_configs:

  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
      #- targets:
      #  - cadvisor:8888
      - targets: ['192.168.100.3:15692']
        labels:
          group: 'rabbitmq-evidence'


  - job_name: reactive-app-evidence
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['192.168.100.3:8081']
        labels:
          group: 'reactive-app-evidence'

  - job_name: springboot-app-evidence
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['192.168.100.7:8080']
        labels:
          group: 'springboot-app-evidence'